In [31]:
! pip install numpy # used to look at our data
! pip install pandas # used to load in our data (a .csv file)

Requirement already satisfied: numpy in /Users/shreyanakum/Downloads/ML101-Code-Examples/.venv/lib/python3.12/site-packages (2.3.2)
Requirement already satisfied: pandas in /Users/shreyanakum/Downloads/ML101-Code-Examples/.venv/lib/python3.12/site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in /Users/shreyanakum/Downloads/ML101-Code-Examples/.venv/lib/python3.12/site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/shreyanakum/Downloads/ML101-Code-Examples/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/shreyanakum/Downloads/ML101-Code-Examples/.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/shreyanakum/Downloads/ML101-Code-Examples/.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/shreyanakum/Downloads/ML101-Code-Examples/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [32]:
import pandas as pd
import numpy as np

# Loading in a Dataset

In [33]:
data = pd.read_csv("board_members.csv")
data.head() # head displasy the first 5 inputs by default

              Name                 Major  Month FavoriteOS  AcademicYear
0     Shreya Nakum      Computer Science      3      Linux             3
1  Jasmine Marwaha      Computer Science      8      MacOS             3
2       Audrey Sun  Software Engineering      4    Windows             2
3       Maan Patel      Computer Science      6      MacOS             3
4          Jay Kim  Computer Engineering     11      MacOS             3

In [34]:
# how would you display the first 10 entries?
data.head(10)

,Name,Major,Month,FavoriteOS,AcademicYear
0,Shreya Nakum,Computer Science,3,Linux,3
1,Jasmine Marwaha,Computer Science,8,MacOS,3
2,Audrey Sun,Software Engineering,4,Windows,2
3,Maan Patel,Computer Science,6,MacOS,3
4,Jay Kim,Computer Engineering,11,MacOS,3
5,Isha Kotalwar,Computer Science,11,MacOS,2
6,Arnav Saharan,Computer Science,2,MacOS,2
7,Sabrina Pukarta,Computer Science Engineering,5,MacOS,4
8,Jason Nguyen,Computer Science,1,MacOS,2
9,Zachary Lai,Computer Science,11,MacOS,4

In ML, we have X and the Y, as you learned
With this dataset, we want to create a model to predict whether or not it is someone's first time at an AI@UCI meeting
Therefore, what will our target be?

# Intro to Numpy

## Characteristics of Our Data

In [ ]:
data = np.array(data)
# splitting our data into our features (X) and target (y)
meeting_X, meeting_y = data[:,:-1], data[:,-1]
# meeting_X = name (STR), major (STR), birthday month (INT), favorite operating system (STR)
# meeting_y = academic year (INT)

### Printing

In [ ]:
# printing all features of X
meeting_X

array([['Shreya Nakum', 'Computer Science', 3, 'Linux'],
       ['Jasmine Marwaha', 'Computer Science', 8, 'MacOS'],
       ['Audrey Sun', 'Software Engineering', 4, 'Windows'],
       ['Maan Patel', 'Computer Science', 6, 'MacOS'],
       ['Jay Kim', 'Computer Engineering', 11, 'MacOS'],
       ['Isha Kotalwar', 'Computer Science', 11, 'MacOS'],
       ['Arnav Saharan', 'Computer Science', 2, 'MacOS'],
       ['Sabrina Pukarta', 'Computer Science Engineering', 5, 'MacOS'],
       ['Jason Nguyen', 'Computer Science', 1, 'MacOS'],
       ['Zachary Lai', 'Computer Science', 11, 'MacOS'],
       ['Andy Choi', 'Computer Science', 12, 'Windows'],
       ['Johnson Nguyen', 'Computer Science', 1, 'Windows'],
       ['David Culciar', 'Computer Science Engineering', 4, 'Linux'],
       ['Julian Aparicio', 'Computer Science', 12, 'MacOS'],
       ['Vyom Shah', 'Computer Science', 10, 'MacOS'],
       ['Naz Atalay', 'Computer Science', 4, 'MacOS'],
       ['Jonathan Pan', 'Computer Science', 12, 'Windows'],
       ['Brandon Tran', 'Computer Science', 1, 'Windows'],
       ['Varun Sunkavalli', 'Computer Science', 8, 'MacOS'],
       ['Houssin Saadeh', 'Computer Science', 8, 'Linux'],
       ['Injila Adil', 'Computer Science', 6, 'MacOS']], dtype=object)

In [ ]:
# printing all target labels of X (the academic year)
meeting_y

array([3, 3, 2, 3, 3, 2, 2, 4, 2, 4, 4, 3, 3, 4, 3, 2, 3, 4, 4, 4, 2],
      dtype=object)

### Shape

We can see the shape of a numpy array by using `.shape`. Here, we see that `meeting_X` is a numpy array with 21 rows and 4 columns, and `meeting_y` is a numpy array with 21 entries.

In [ ]:
meeting_X.shape

(21, 4)

In [39]:
meeting_y.shape

(21,)

In [ ]:
# how many data points are in X?
len(meeting_X)

21

In [ ]:
# how many features does one data point have?
len(meeting_X[0])

4

In [ ]:
# how many different classes do we have?
print(np.unique(meeting_y))

[2 3 4]

## Indexing
Similar to indexing in a Python list object, you can index a numpy array.

### Basic Indexing
This is how you can access any data point or feature of your `X`. Each index corresponds to an entry.

In [85]:
# first row of our data
meeting_X[0]

array(['Shreya Nakum', 'Computer Science', 3, 'Linux'], dtype=object)

In [86]:
# first two rows
meeting_X[0:2]

array([['Shreya Nakum', 'Computer Science', 3, 'Linux'],
       ['Jasmine Marwaha', 'Computer Science', 8, 'MacOS']], dtype=object)

In [87]:
# another way to say first row
meeting_X[0, :]

array(['Shreya Nakum', 'Computer Science', 3, 'Linux'], dtype=object)

In [88]:
# first column
meeting_X[:,0]

array(['Shreya Nakum', 'Jasmine Marwaha', 'Audrey Sun', 'Maan Patel',
       'Jay Kim', 'Isha Kotalwar', 'Arnav Saharan', 'Sabrina Pukarta',
       'Jason Nguyen', 'Zachary Lai', 'Andy Choi', 'Johnson Nguyen',
       'David Culciar', 'Julian Aparicio', 'Vyom Shah', 'Naz Atalay',
       'Jonathan Pan', 'Brandon Tran', 'Varun Sunkavalli',
       'Houssin Saadeh', 'Injila Adil'], dtype=object)

In [89]:
# first target label of first data point
meeting_y[0]

4

In [90]:
# set a value
meeting_y[0] = 3

In [91]:
meeting_y[0]

3

### Indexing via Slicing
Python "slicing" allows us to access entire rows or columns. We can also access contiguous rows & columns.

In [ ]:
# first 5 rows of meeting_X
meeting_X[:5, :]

array([['Shreya Nakum', 'Computer Science', 3, 'Linux'],
       ['Jasmine Marwaha', 'Computer Science', 8, 'MacOS'],
       ['Audrey Sun', 'Software Engineering', 4, 'Windows'],
       ['Maan Patel', 'Computer Science', 6, 'MacOS'],
       ['Jay Kim', 'Computer Engineering', 11, 'MacOS']], dtype=object)

In [ ]:
# the 10th to *14th* rows of meeting_X
meeting_X[10:15, :]

array([['Andy Choi', 'Computer Science', 12, 'Windows'],
       ['Johnson Nguyen', 'Computer Science', 1, 'Windows'],
       ['David Culciar', 'Computer Science Engineering', 4, 'Linux'],
       ['Julian Aparicio', 'Computer Science', 12, 'MacOS'],
       ['Vyom Shah', 'Computer Science', 10, 'MacOS']], dtype=object)

In [ ]:
# the 1st to 3rd rows and 1st to 3rd columns (features)
meeting_X[1:4, 1:4]

array([['Computer Science', 8, 'MacOS'],
       ['Software Engineering', 4, 'Windows'],
       ['Computer Science', 6, 'MacOS']], dtype=object)

In [92]:
# the last row of meeting_X
meeting_X[-1, :]

array(['Injila Adil', 'Computer Science', 6, 'MacOS'], dtype=object)

In [ ]:
# the last 3 rows of meeting_X
meeting_X[-3:, :]

array([['Varun Sunkavalli', 'Computer Science', 8, 'MacOS'],
       ['Houssin Saadeh', 'Computer Science', 8, 'Linux'],
       ['Injila Adil', 'Computer Science', 6, 'MacOS']], dtype=object)

In [ ]:
# first three columns
meeting_X[:, :-1]

array([['Shreya Nakum', 'Computer Science', 3],
       ['Jasmine Marwaha', 'Computer Science', 8],
       ['Audrey Sun', 'Software Engineering', 4],
       ['Maan Patel', 'Computer Science', 6],
       ['Jay Kim', 'Computer Engineering', 11],
       ['Isha Kotalwar', 'Computer Science', 11],
       ['Arnav Saharan', 'Computer Science', 2],
       ['Sabrina Pukarta', 'Computer Science Engineering', 5],
       ['Jason Nguyen', 'Computer Science', 1],
       ['Zachary Lai', 'Computer Science', 11],
       ['Andy Choi', 'Computer Science', 12],
       ['Johnson Nguyen', 'Computer Science', 1],
       ['David Culciar', 'Computer Science Engineering', 4],
       ['Julian Aparicio', 'Computer Science', 12],
       ['Vyom Shah', 'Computer Science', 10],
       ['Naz Atalay', 'Computer Science', 4],
       ['Jonathan Pan', 'Computer Science', 12],
       ['Brandon Tran', 'Computer Science', 1],
       ['Varun Sunkavalli', 'Computer Science', 8],
       ['Houssin Saadeh', 'Computer Science', 8],
       ['Injila Adil', 'Computer Science', 6]], dtype=object)

In [ ]:
# get rows 1, 5, 9 from meeting_X
fetch_rows = [1, 5, 9]
meeting_X[fetch_rows, :]

array([['Jasmine Marwaha', 'Computer Science', 8, 'MacOS'],
       ['Isha Kotalwar', 'Computer Science', 11, 'MacOS'],
       ['Zachary Lai', 'Computer Science', 11, 'MacOS']], dtype=object)

In [69]:
# get 1st and last column from meeting_X
fetch_cols = [0, -1]
meeting_X[:, fetch_cols]

array([['Shreya Nakum', 'Linux'],
       ['Jasmine Marwaha', 'MacOS'],
       ['Audrey Sun', 'Windows'],
       ['Maan Patel', 'MacOS'],
       ['Jay Kim', 'MacOS'],
       ['Isha Kotalwar', 'MacOS'],
       ['Arnav Saharan', 'MacOS'],
       ['Sabrina Pukarta', 'MacOS'],
       ['Jason Nguyen', 'MacOS'],
       ['Zachary Lai', 'MacOS'],
       ['Andy Choi', 'Windows'],
       ['Johnson Nguyen', 'Windows'],
       ['David Culciar', 'Linux'],
       ['Julian Aparicio', 'MacOS'],
       ['Vyom Shah', 'MacOS'],
       ['Naz Atalay', 'MacOS'],
       ['Jonathan Pan', 'Windows'],
       ['Brandon Tran', 'Windows'],
       ['Varun Sunkavalli', 'MacOS'],
       ['Houssin Saadeh', 'Linux'],
       ['Injila Adil', 'MacOS']], dtype=object)

### Logical Indexing
You can index an array depending on specifications of the array's content. This allows for a boolean to be returned and for us to inspect parts of the data that follow some sort of binary "rule."

In [ ]:
bday_months = meeting_X[:,2] # the 2nd column is the birthday month feature
bday_months # all birthday months

array([3, 8, 4, 6, 11, 11, 2, 5, 1, 11, 12, 1, 4, 12, 10, 4, 12, 1, 8, 8,
       6], dtype=object)

In [ ]:
# how many board members are born in the latter half of the year?
bday_months > 6

array([False,  True, False, False,  True,  True, False, False, False,
        True,  True, False, False,  True,  True, False,  True, False,
        True,  True, False])

In [ ]:
# what are the bday months of those born in the latter half of the year?
bday_months[bday_months > 6]

array([8, 11, 11, 11, 12, 12, 10, 12, 8, 8], dtype=object)

In [ ]:
# who are the board members born in the latter half of the year?
meeting_X[bday_months > 6]

array([['Jasmine Marwaha', 'Computer Science', 8, 'MacOS'],
       ['Jay Kim', 'Computer Engineering', 11, 'MacOS'],
       ['Isha Kotalwar', 'Computer Science', 11, 'MacOS'],
       ['Zachary Lai', 'Computer Science', 11, 'MacOS'],
       ['Andy Choi', 'Computer Science', 12, 'Windows'],
       ['Julian Aparicio', 'Computer Science', 12, 'MacOS'],
       ['Vyom Shah', 'Computer Science', 10, 'MacOS'],
       ['Jonathan Pan', 'Computer Science', 12, 'Windows'],
       ['Varun Sunkavalli', 'Computer Science', 8, 'MacOS'],
       ['Houssin Saadeh', 'Computer Science', 8, 'Linux']], dtype=object)

In [83]:
upperclassmen = meeting_y > 2 # how many board members are upperclassmen?
upperclassmen

array([ True,  True, False,  True,  True, False, False,  True, False,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False])

In [84]:
# who is an upperclassmen?
meeting_y[upperclassmen]

array([4, 3, 3, 3, 4, 4, 4, 3, 3, 4, 3, 3, 4, 4, 4], dtype=object)

In [105]:
meeting_X[upperclassmen]

array([['Shreya Nakum', 'Computer Science', 3, 'Linux'],
       ['Jasmine Marwaha', 'Computer Science', 8, 'MacOS'],
       ['Maan Patel', 'Computer Science', 6, 'MacOS'],
       ['Jay Kim', 'Computer Engineering', 11, 'MacOS'],
       ['Sabrina Pukarta', 'Computer Science Engineering', 5, 'MacOS'],
       ['Zachary Lai', 'Computer Science', 11, 'MacOS'],
       ['Andy Choi', 'Computer Science', 12, 'Windows'],
       ['Johnson Nguyen', 'Computer Science', 1, 'Windows'],
       ['David Culciar', 'Computer Science Engineering', 4, 'Linux'],
       ['Julian Aparicio', 'Computer Science', 12, 'MacOS'],
       ['Vyom Shah', 'Computer Science', 10, 'MacOS'],
       ['Jonathan Pan', 'Computer Science', 12, 'Windows'],
       ['Brandon Tran', 'Computer Science', 1, 'Windows'],
       ['Varun Sunkavalli', 'Computer Science', 8, 'MacOS'],
       ['Houssin Saadeh', 'Computer Science', 8, 'Linux']], dtype=object)

In [107]:
# how many members are upperclassmen?
len(meeting_X[upperclassmen])

15

### Feature Statistics (Optional)
Numpy has a number of functions you can use to find out the statistics of your data, primarily for you input (X) data.

In [93]:
bday_months = meeting_X[:,2] # the 2nd column is the birthday month feature
bday_months # all birthday months

array([3, 8, 4, 6, 11, 11, 2, 5, 1, 11, 12, 1, 4, 12, 10, 4, 12, 1, 8, 8,
       6], dtype=object)

In [ ]:
# what is the average bday month?
np.mean(meeting_X[:,2])

np.float64(6.666666666666667)

In [96]:
# what are the mean, variance, standard deviation, min, and max of bday months?
print(f'Mean: {np.mean(meeting_X[:,2], axis=0)}') # axis = 0 means going up and down the column; axis = 1 means going left and right
print(f'Variance: {np.var(meeting_X[:,2])}')
print(f'Standard Deviation: {np.std(meeting_X[:,2])}')
print(f'Minimum: {min(meeting_X[:,2])}')
print(f'Maximum: {max(meeting_X[:,2])}')

Mean: 6.666666666666667
Variance: 14.984126984126988
Standard Deviation: 3.8709336062669673
Minimum: 1
Maximum: 12

In [98]:
# what are the mean, variance, standard deviation, min, and max of bday months for board members who like Windows?
print(f'Mean: {np.mean(meeting_X[meeting_X[:,3] == 'Windows'][:,2], axis=0)}') # axis = 0 means going up and down the column; axis = 1 means going left and right
print(f'Variance: {np.var(meeting_X[meeting_X[:,3] == 'Windows'][:,2])}')
print(f'Standard Deviation: {np.std(meeting_X[meeting_X[:,3] == 'Windows'][:,2])}')
print(f'Minimum: {min(meeting_X[meeting_X[:,3] == 'Windows'][:,2])}')
print(f'Maximum: {max(meeting_X[meeting_X[:,3] == 'Windows'][:,2])}')

Mean: 6.0
Variance: 25.2
Standard Deviation: 5.019960159204453
Minimum: 1
Maximum: 12

In [99]:
# what are the mean, variance, standard deviation, min, and max of bday months for board members who like MacOS?
print(f'Mean: {np.mean(meeting_X[meeting_X[:,3] == 'MacOS'][:,2], axis=0)}') # axis = 0 means going up and down the column; axis = 1 means going left and right
print(f'Variance: {np.var(meeting_X[meeting_X[:,3] == 'MacOS'][:,2])}')
print(f'Standard Deviation: {np.std(meeting_X[meeting_X[:,3] == 'MacOS'][:,2])}')
print(f'Minimum: {min(meeting_X[meeting_X[:,3] == 'MacOS'][:,2])}')
print(f'Maximum: {max(meeting_X[meeting_X[:,3] == 'MacOS'][:,2])}')

Mean: 7.3076923076923075
Variance: 12.21301775147929
Standard Deviation: 3.4947128281847837
Minimum: 1
Maximum: 12

In [ ]:
# the mean of an entire row
print(f'Mean: {np.mean(meeting_X[0], axis=0)}')
print(f'Standard Deviation: {np.std(meeting_X[0], axis=0)}')